[tools]
aws-cli = "latest"
chezmoi = "latest"
duckdb = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
go = "latest"
java = "corretto-21"
jq = "latest"
neovim = "latest"
node = "24"
ripgrep = "latest"
rust = "latest"
starship = "latest"
uv = "latest"
zola = "latest"
